### ISSUE TITLE
Mobile Navbar is too high in landscape mode

### ISSUE THREAD

**Issue by cdfa** [svsticky/static-sticky#101]
This also causes the sub-menu to be hidden.
![screen shot 2019-02-05 at 12 19 02](https://user-images.githubusercontent.com/8250462/52270157-61627900-2940-11e9-8a97-ba64e5b04fc6.png)

**Comment by cdfa** [comment]
Fixed in https://github.com/svsticky/static-sticky/commit/fbab5540517cd35efe9d51ee530a6f0de8d66107
Although this might break again if we change the navbar height.

**Comment by emielvanrijn** [comment]
Yes we should look into dynamic heights in the future :)...
