### ISSUE TITLE
Enrollment button doesn't work

### ISSUE THREAD

**Issue by cdfa** [svsticky/static-sticky#110]
This is a really weird one. From my own testing it seems like the browser waits a little bit before following the link and then 'can't find it anymore', because it was moved by the animation. Could probably be hotfixed by triggering the link from the OnTouchEnd event or putting a invisible `<a>` over everything while the card is transitioning out. I would really like to know why this is happening though. Any thought @emielvanrijn @Phavion ?

**Comment by Phavion** [comment]
For me this is only the case in mobile view, same at your side?

**Comment by cdfa** [comment]
Yes. You need to have touch simulation enabled too.

**Comment by Phavion** [comment]
Ah I notice yeah. To make it more interesting: in chrome the button is not clickable at all... whether in firefox it works, but with a delay.

**Comment by emielvanrijn** [comment]
I think I said this yesterday in slack? Or is this something else? I thought this could be a thing because of the touchlistener which is applied to the whole div?

**Comment by emielvanrijn** [comment]
As a fix, i think we should just add a button just beneath the wrapper which triggers the animation for now?

**Comment by cdfa** [comment]
Yes, you did mention it in Slack yesterday, but I made an issue about it here, because I don't have time to really work on it.
A button that triggers the animation might solve the problem, but only because you won't be making the card turn and opening a link at the same time.

**Comment by emielvanrijn** [comment]
Maybe we can TurnReveal on the complete poster, but TurnHide on only the space of the card above the button by putting title and description in a seperate div? TurnReveal now triggers on the whole container by the way, not only the poster/card...

**Comment by cdfa** [comment]
Hmm, I think that would require us to rework `<TurnReveal>` quite a bit. I think the button solution is better.
