### ISSUE TITLE
Replace all plain `<div>`'s with React fragments

### ISSUE THREAD

**Issue by cdfa** [svsticky/static-sticky#115]
As per the (new #116) contributing guidelines.

**Comment by urmil22** [comment]
@cdfa @Riscky @SilasPeters Can you assign this to me?

**Comment by SilasPeters** [comment]
Sure! Just double checking though: @stickyPiston is this still in line with our current vision of the project? This issue is 6 years old

Anyway, nice of you to help out!

**Comment by stickyPiston** [comment]
It is still in line with our vision, however most (if not all) of the plain `<div>`s in the project are there because of stylistic reasons or for compatibility with the style library we use. So this issue is not very relevant currently.
