### ISSUE TITLE
Add banner ad incosistency.

### ISSUE THREAD

**Issue by RobinSikkens** [svsticky/static-sticky#121]
Sometimes upon reloading the page one of the adds that is cycled through in the ad banner is replaced by a duplicate ad.

e.g. in an add pool of [A, B, C, D] the add reel will sometimes shows [A, B, C, C] or some other permutation with a duplicate.

Steps to reproduce:
- Refresh page until error occurs

**Comment by Phavion** [comment]
This seems to not occur anymore. After a lot of reloads and tries, this issue is not reproducable anymore
