### ISSUE TITLE
Ad banners are not links

### ISSUE THREAD

**Issue by tomwassenberg** [svsticky/static-sticky#123]
The ads that are scrolling by on the frontpage are not linking to anything. I assume these have to link to a page that's specified by the partner? Like it used to be on the [old website](https://old.svsticky.nl/).

(Tested in Fx and Chrome,)

**Comment by Phavion** [comment]
Not really a bug as Stef told me on showing it to him that it was not needed.

**Comment by tomwassenberg** [comment]
Really? Well ok, then there's no problem I guess.
