### ISSUE TITLE
Minor copy issues/suggestions

### ISSUE THREAD

**Issue by RCdeWit** [svsticky/static-sticky#127]
Small items, ordered by page:

- [x] Home
-- Eerstvolgende Activiteit uses inconsistent capitalisation (Uitgelichte vacature).
- [x] Besturen
-- "Huidige bestuur" rather than "Huidig bestuur"
-- "Oud-besturen" or "Oude besturen"
- [x] Contact
-- Would use "Sponsoren" rather than "Sponsors"
- [x] Lidmaatschap
-- Run-on sentence bij "Inschrijven .. zolang je studie duurt."
- [x] Statuten etc.
-- Perhaps rename this item to "Documents"
- [x] Medezeggenschap
-- Refer to relevant webpages?
- [x] Links
-- Duplicate with Medezeggenschap.

**Comment by cdfa** [comment]
This seems to be fixed, but I don't know exactly where.
