### ISSUE TITLE
Partner page does not show jobs

### ISSUE THREAD

**Issue by GlennStewart125** [svsticky/static-sticky#129]
On the partner page of Geodan (https://svsticky.nl/partners/geodan). The jobs linked to Geodan are not shown. They are linked in contentful and are shown on the jobs page.

When opening a job page, clicking on the logo does redirect you to the partner page.

**Comment by cdfa** [comment]
This seems to be fixed, but I don't know exactly where. (@Phavion might know)

**Comment by Phavion** [comment]
Was a hotfix directly committed to development.
