### ISSUE TITLE
Automate prettification even more

### ISSUE THREAD

**Issue by cdfa** [svsticky/static-sticky#13]
In my auto-prettier branch (and hopefully soon in development), the code is prettified with prettier and precise-commits on a precommit hook. This prettifies the staged code per character, but does not stage any prettied up code. This feature is yet to be added to the precise-commits package ([#7](https://github.com/nrwl/precise-commits/issues/7)). I looked at the code and it doesn't look to complicated and it would be nice to have to commit be aborted if there we're any prettifications (like the last comment on the issue suggests). On the other hand there might be more important thinks to work on. What do you think @emielvanrijn ?

**Comment by emielvanrijn** [comment]
Good stuff
