### ISSUE TITLE
Redesign footer

### ISSUE THREAD

**Issue by maartenberg** [svsticky/static-sticky#137]
![image](https://user-images.githubusercontent.com/15868836/81418327-cb259000-914c-11ea-9060-0857a201e391.png)
Mockup of a new footer, opinions are very welcome

TODO:
- [ ] Add current contact details to Contact page
- [x] Add About Us page
- [ ] Remove Github from links
- [ ] replace footer content
- [ ] Make sure everything is multilingual

**Comment by dbrunek** [comment]
Footer needs a complete redesign. The information in the current footer needs to be moved to a page.

**Comment by Riscky** [comment]
![image](https://user-images.githubusercontent.com/15868836/81418327-cb259000-914c-11ea-9060-0857a201e391.png)
Mockup of a new footer, opinions are very welcome

**Comment by Mstiekema** [comment]
I'd recommend putting the three icons in the center of the footer. Looks good!
