### ISSUE TITLE
Vacature page is not linked to accompanying partner page

### ISSUE THREAD

**Issue by GlennStewart125** [svsticky/static-sticky#139]
Partner pages are no longer shows the available vacancies.

Example:
https://svsticky.nl/partners/gendx
https://svsticky.nl/vacatures/software-developer-tester

When creating a new test partner and test vacancy containing the minimal amount of information needed, the vacancy is not shown in the partner page. So this problem is not specific for GenDx.

**Comment by Phavion** [comment]
Works for me :)

**Comment by Riscky** [comment]
This is a recurring problem, at this moment the only example I could find is gendx.
There is a vacancy that should be linked but is not.

**Comment by Riscky** [comment]
There is a workaround for this issue:

- unpublish de partner page (breaking the build)
- republish the partner page

The partner page should rebuild when a new vacancy is linked, but this doesn't happen apparently.

**Comment by Riscky** [comment]
The new build system does not rely on a cache and as such these problems should be gone now
