### ISSUE TITLE
Adding a theme-color meta tag 

### ISSUE THREAD

**Issue by Daruso** [svsticky/static-sticky#147]
## What is this about?
Adding the following line to the top of the HTML file should color the omnibar on Chrome Android, maybe also on iOS, with the proper color also present on the website.

`<meta name="theme-color" content="#C53F78" />`

where the color should be based on the current board color

## What value does this have?
I believe adding this line (or something that acomplishes the same) will give the website more visual cohesion on Chrome on Android, and possibly on Chrome on iOS.

**Comment by Riscky** [comment]
We cannot at this moment set this property from contentful, making it hard to maintain
