### ISSUE TITLE
Menu items have weird ordering

### ISSUE THREAD

**Issue by Mstiekema** [svsticky/static-sticky#182]
The items in the menu are sorted by reverse alphabetical order. This causes the location of the menu items to switch when you change the language. Make it so the order of the items are static.

**Comment by Mstiekema** [comment]
The ordering of navbar itself is correct now, but the items link to the incorrect pages.

![image](https://user-images.githubusercontent.com/16525696/75523597-9be7f980-5a0c-11ea-92c1-0ae9b00f6e61.png)

**Comment by Riscky** [comment]
fixed with #196
