### ISSUE TITLE
Decide how to host the website

### ISSUE THREAD

**Issue by emielvanrijn** [svsticky/static-sticky#20]
At this very moment, the website is hosted on netlify (https://compassionate-northcutt-c017f9.netlify.com/). It automatically builds from master, and it creates a preview deploy from development. We can add our own domain to netlify. It also automatically rebuilds from new contentful content via a webhook. So, this solution seems perfect to me, but maybe there are some things that I am not aware of? 

Let us discuss!

**Comment by tomwassenberg** [comment]
What are the requirements here? Maybe all parties can chime in, listing what they need to be able to do in practice:

- @svsticky/commit: Working on the website, deploy to staging(?) and/or production(?), ...
- The board (@Ckef / @GlennStewart125 / @zoebxl): Maintaining the content, ...
- @svsticky/it-crowd: Availability, security, ...

**Comment by emielvanrijn** [comment]
Yes that is why I opened this issue :). Would love to hear your ideas!

**Comment by cdfa** [comment]
> It automatically builds from master, and it creates a preview deploy from development. We can add our own domain to netlify. It also automatically rebuilds from new contentful content via a webhook.

This sounds pretty awesome. Don't know what else I would want

**Comment by cdfa** [comment]
Oops didn't mean to close

**Comment by arianvp** [comment]
I would prefer hosting it on `sadserver`  .    Setting up push-to-deploy for that wouldn't be too hard. We used to do that for Koala as well on the old server.

**Comment by arianvp** [comment]
We can also just keep using netlify for development builds

**Comment by tomwassenberg** [comment]
In the last sessions I think we decided to set up a webhook listener on prod+staging, and configure that webhook in Contentful. Then we retain the ease of Netlify for development, but host the rest in our own infrastructure.

Would be nice if we can use what's developing [here](https://github.com/svsticky/aas) for the webhook listener.

**Comment by emielvanrijn** [comment]
So, everything pushed to `master` will be build and will run on svsticky.nl. Everything pushed to `development` will be build by Netlify as a preview, also running as a test on PR's etc.
