### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by Riscky** [svsticky/static-sticky#200]
#### Changes in Contentful

- [x] Board: Members (titles are untranslated)
- [x] Board Member: Role
- [x] Board Member: Type of contact
- [x] Committee: Description
- [x] Dispute: Description
- [x] Job listing: Summary
- [x] Job listing: Listing content
- [x] Partner: Description

#### Changes in the code

- [x] Board: Name
- [x] Societies: Title and page title (#248 should fix this one)

#### Changes on both sides

- [ ] Drinks: Day

#### Won't do

- [ ] Banner Logo: Title (reason: unused)

**Comment by mivanessen** [comment]
- [ ] Banner Logo: Title 
- [ ] Board Member: Topic
- [ ] Board Member: Role
- [ ] Board Member: Type of contact
- [ ] Committee: Description
- [ ] Dispute: Description
- [ ] Drinks: Day
- [ ] Job listing: Summary
- [ ] Job listing: Listing content (for company to send translation)
- [ ] Partner: Description

**Comment by Riscky** [comment]
only one translation left, creating a new issue for that one
