### ISSUE TITLE
Failed image render from markdown on /partners/bol-com page

### ISSUE THREAD

**Issue by niekh1234** [svsticky/static-sticky#284]
When visiting this page,
"`![Bol.com header 19/20](//images.ctfassets.net/7cqe14fu3dhm/3ShdsDgwKHcgt4f0wypTC8/91e598d225c61c2ddd055093f5c68fa2/Extra_afbeelding_2.jpg)`" is rendered instead of the image.

It is rendered as a `<pre>` element.

![Screenshot from 2021-04-23 12-33-44](https://user-images.githubusercontent.com/34717999/115859637-c24ace80-a430-11eb-8835-b98576e6e4d2.png)

**Comment by Mstiekema** [comment]
Thanks for letting us know! This has been fixed.
