### ISSUE TITLE
Cards around contentful content

### ISSUE THREAD

**Issue by cdfa** [svsticky/static-sticky#29]
It might be a personal thing, but i think having a card around the contentful content is quite ugly, especially because the top and bottom overlap slightly with the header and footer. Just no card would look a lot cleaner imo.

**Comment by Phavion** [comment]
The fact that they overlap slightly was fixed on friday by @emielvanrijn and me. Imo it looks good with the padding.

**Comment by emielvanrijn** [comment]
I must admit we should be a bit more conservative with the usage of cards. We can try think about this next working session.

**Comment by emielvanrijn** [comment]
We discussed this today, and concluded that we will remove the card around EVERY content that is coming in from contentful, and only use cards to emphasize specific content and links
