### ISSUE TITLE
Form to submit "grensoverschrijdend gedrag"

### ISSUE THREAD

**Issue by Jelte-Akker** [svsticky/static-sticky#321]
We want a page like this: https://www.a-eskwadraat.nl/Vereniging/Meldpunt 
Here people can submit this which will be forwarded to the mails of the confidants!

**Comment by JustNireon** [comment]
We can use https://formsubmit.co/ for this.

**Comment by sam32123** [comment]
as https://github.com/svsticky/fallacious-rooster/tree/master now exists, I beleave this issue can be closed
