### ISSUE TITLE
Outdated referral link in the dropdown menu

### ISSUE THREAD

**Issue by GitBreax** [svsticky/static-sticky#339]
There has been a change of book supplier and thus the link to the suppliers webpage needs to be updated. 
It seems this cannot be done via contentful. 
So it probably needs to be changed hardcoded in the html. 
If it is changed to svstick./nl/boeken or svsticky.nl/books (for english) it can easily be updated via doorfeegluik

**Comment by Jelte-Akker** [comment]
resolved
