### ISSUE TITLE
Fill homepage with cool information and widgets

### ISSUE THREAD

**Issue by Agarwaemben** [svsticky/static-sticky#41]
- [x] Partnerbanner
- [x] News
- [x] Upcoming activities
- [x] Time, date, place of drinks
- [x] Featured job listing

**Comment by emielvanrijn** [comment]
Yeboiii, maybe we can extend this issue with a checklist of items that we would like to see on the homepage. Let's make it a discussion: please comment your additions :).

**Comment by emielvanrijn** [comment]
I just added mine :)

**Comment by cdfa** [comment]
Can this be closed?

**Comment by emielvanrijn** [comment]
Yes I can think of no more widgets to be added atm
