### ISSUE TITLE
Rescale posters uploaded to Koala

### ISSUE THREAD

**Issue by Ckef** [svsticky/static-sticky#49]
Currently it isn't enforced for posters to be the same scale. This causes difficulties when trying to consistently render posters at the same position and size. The easiest fix is to rescale (crop or enlargen) the .pdf file when it is uploaded to Koala. All posters should be A3 format.

**Comment by Ckef** [comment]
Haha wrong repository.

**Comment by emielvanrijn** [comment]
Haha fixed in #48
