### ISSUE TITLE
Add mobile navigation

### ISSUE THREAD

**Issue by cdfa** [svsticky/static-sticky#50]

**Comment by emielvanrijn** [comment]
I had a specific idea in mind for this, so if you're okay with it, I would like to take this one :)...

**Comment by cdfa** [comment]
Ow, okay. I did start looking into it and found [this](https://codesandbox.io/s/325y47xk36) quite good looking code, so maybe that will help you as well.

**Comment by cdfa** [comment]
Fixed in #67
