### ISSUE TITLE
Lazy-load images

### ISSUE THREAD

**Issue by emielvanrijn** [svsticky/static-sticky#54]
Pages with a lot of images are not very responsive at the moment  on slow connections (looking at you activiteiten-page...). We should lazy-load these images for UX reasons :).

**Comment by cdfa** [comment]
I see the images slowly filling in top to bottom, but before that has happened the cards do flip and i can scroll, so that seems pretty responsive to me.

**Comment by Phavion** [comment]
Yes, but it would be awesome to show some kind of loading button when they're still loading to prevent viewing half loading images.

**Comment by cdfa** [comment]
Is that really a problem? I for one like to see as much as possible when it's available, even if it's only part of it.

**Comment by emielvanrijn** [comment]
The problem mainly was that the pocture are just too big. With a new koala update, there will be a thumbnail available 9th of the size :). That should speed thing up a lot, lighthouse audit gave images as the main bottlenack for loading, so I am hypee to see how it will improve :)...

**Comment by emielvanrijn** [comment]
Closing as there won't be that much pictures anywhere and with the new thumbnail available soon in the API, this will be much less of a problem
