### ISSUE TITLE
Styling walkthrough

### ISSUE THREAD

**Issue by emielvanrijn1** [svsticky/static-sticky#55]
Before we put the new website live, we should go through the website and fix some minor styling-issues. 

The following things have emerged during development to be looked at:
- [x] contact information as grid instead of long list
- [ ] option to enlarge board photos
- [x] images inserted in markdown of articles don't show as images on the homepage
- [ ] images inserted in markdown should have a maximum size
- [x] let's fix that footer in chrome at some point
- [x] there is no footer on the activiteiten, disputen, contact, besturen, samenwerking, vacatures and partner pages

If some of these issues only appear in chrome:
- [x] Fix them in chrome :)

**Comment by Ckef** [comment]
Comment on some points:
- "images insertec in markdown of articles don't show as images on the homepage": We suspect markdown is simply rendered as text and not as markdown on the homepage? (when you go the articles themselves it does render as markdown however)
- "images inserted in markdown should have a maximum size": When previewing the markdown in contentful it shows a section in which the image is centered and resized, we would like to see this kind of layout on the actual site as well. Something similar for the layout of articles on the homepage.

**Comment by Ckef** [comment]
Also I removed the "Show widgets on other pages" thingamabob ;)

**Comment by Ckef** [comment]
I've added this issue to the Alpha Release milestone, but not everything has to be done for the release in my opinion. Listing the features we do want to see in the release:

- [ ] images inserted in markdown of articles don't show as images on the homepage
- [ ] images inserted in markdown should have a maximum size
- [ ] let's fix that footer in chrome at some point
- [ ] there is no footer on the activiteiten, disputen, contact, besturen, samenwerking, vacatures and partner pages

**Comment by emielvanrijn** [comment]
There is a footer for activiteiten etc, but just not on chrome ;).
