### ISSUE TITLE
Committee page

### ISSUE THREAD

**Issue by Ckef** [svsticky/static-sticky#56]
We would like to see a page for committees. This page should show all committees of Sticky with:

- Name of the committee
- Logo of the committee
- A short description of what the committee does
- An optional photo of all members of the committee

As the last point suggests, a photo can be added for every single committee. However this is optional, not every committee _has_ to add a photo.

**Comment by maartenberg** [comment]
(Almost) all committees have an email address / a mailing list to reach the members, it might be useful to show this address as well on the page.
