### ISSUE TITLE
Grid-like structure for text only pages

### ISSUE THREAD

**Issue by Ckef** [svsticky/static-sticky#63]
Some text only pages contain small texts only with a lot of newlines that could be arranged nicely into blocks or a grid. Currently I'm looking at the Contact page, it would be nice if some of these blocks could be arranged horizontally and not just vertically. So we have a grid-like structure like on the Disputen, Activiteiten or Besturen pages.

In contentful you edit a markdown file to add text to a page. In markdown it is impossible to horizontally divide the text into a grid. This can be done with JSX, but not all board members know how to use this.

**Comment by emielvanrijn** [comment]
Please leave these comments in #55 :)...
