### ISSUE TITLE
White navbar after hovering submenu's

### ISSUE THREAD

**Issue by Phavion** [svsticky/static-sticky#93]
On beta.svsticky.nl the navbar becomes white after the user hovers over a submenu. This happens in both Chrome and firefox. Weirdly enough this does not happen on a local build with 'npx gatsby serve'

**Comment by Phavion** [comment]
Nvm, it also happens locally....

**Comment by emielvanrijn** [comment]
A little more experimenting with this, I also found that the card on a jobitem view loses its padding when hovering on the navbar, lol...

**Comment by cdfa** [comment]
Workaround in https://github.com/svsticky/static-sticky/commit/270c697415d9d36c9812770cb28c68d09ea62c8d
